package com.newland.paas.paasservice.sysmgr.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-09-13T20:20:03.949+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "UpdateAppAcctSoap",
                  wsdlLocation = "file:/Users/chris_refiled/Desktop/work/paas/java/paas-service/sysmgr/src/main/java/com/newland/paas/paasservice/sysmgr/ws/UpdateAppAcctSoap.wsdl",
                  targetNamespace = "UpdateAppAcctSoap")
public class UpdateAppAcctSoap_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("UpdateAppAcctSoap", "UpdateAppAcctSoap");
    public final static QName UpdateAppAcctSoapSOAP = new QName("UpdateAppAcctSoap", "UpdateAppAcctSoapSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/chris_refiled/Desktop/work/paas/java/paas-service/sysmgr/src/main/java/com/newland/paas/paasservice/sysmgr/ws/UpdateAppAcctSoap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UpdateAppAcctSoap_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/chris_refiled/Desktop/work/paas/java/paas-service/sysmgr/src/main/java/com/newland/paas/paasservice/sysmgr/ws/UpdateAppAcctSoap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UpdateAppAcctSoap_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UpdateAppAcctSoap_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateAppAcctSoap_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UpdateAppAcctSoap_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UpdateAppAcctSoap_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UpdateAppAcctSoap_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UpdateAppAcctSoap
     */
    @WebEndpoint(name = "UpdateAppAcctSoapSOAP")
    public UpdateAppAcctSoap getUpdateAppAcctSoapSOAP() {
        return super.getPort(UpdateAppAcctSoapSOAP, UpdateAppAcctSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateAppAcctSoap
     */
    @WebEndpoint(name = "UpdateAppAcctSoapSOAP")
    public UpdateAppAcctSoap getUpdateAppAcctSoapSOAP(WebServiceFeature... features) {
        return super.getPort(UpdateAppAcctSoapSOAP, UpdateAppAcctSoap.class, features);
    }

}
