apiVersion: v1
kind: Service
metadata:
  name: activiti-flow
  namespace: manage
spec:
  type: ClusterIP
  selector:
    app: activiti-flow-app
  ports:
  - name: activiti-flowapphttp
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activiti-flow
  namespace: manage
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: activiti-flow-app
        track: stable
    spec:
      securityContext:
        runAsUser: 2000
      containers:
      - name: activiti-flow
        image: 172.32.150.15/newland/nl.paas.activiti-flow:image_version
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 350
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5  
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: njtest101
        - name: JVM_OPTS
          value: "-XX:MaxRAMFraction=2"
        - name: LOG_PATH
          value: "/nl/paas/jdklogs"
        ports:
        - containerPort: 8080
        resources:
           requests:
             cpu: 0.5
             memory: 2Gi
           limits:
             cpu: 0.5
             memory: 2Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: localpath
          mountPath: /nl/paas
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: localpath
        hostPath:
          path: /dcoslog/nl/paas