apiVersion: v1
kind: Service
metadata:
  name: sysmgr
  namespace: manage
spec:
  type: NodePort
  selector:
    app: sysmgr
  ports:
  - name: sysmgrhttp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32007
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysmgr
  namespace: manage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sysmgr
        track: stable
    spec:
      containers:
      - name: sysmgr
        image: harbor.paas.nl:5000/paas_platform/nl.paas.sysmgr:2.3
        imagePullPolicy: Always
        env:
        - name: PF_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SPRING_PROFILES_ACTIVE
          value: dev93
        - name: JVM_OPTS
          value: "-XX:MaxRAMFraction=2"
        - name: LOG_PATH
          value: "/nl/paas/jdklogs"
        ports:
        - containerPort: 8080
        resources:
           requests:
             cpu: 1
             memory: 3Gi
           limits:
             cpu: 1
             memory: 3Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: localpath
          mountPath: /nl/paas
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: localpath
        hostPath:
          path: /dcoslog/nl/paas