server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    connectionProperties: tns=LOCAL
    filters: LOCAL
    url: jdbc:oracle:thin:@190.168.141.99:1521:jmcc01
    username: paasapp
    password: Paas1015
    initial-size: 3
    max-active: 5
    min-idle: 1
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL