server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    connectionProperties: tns=LOCAL
    filters: LOCAL
    url: jdbc:oracle:thin:@10.32.38.43:1521/platdb
    username: paas
    password: epyY2jb28x83mp5
    initial-size: 3
    max-active: 5
    min-idle: 1
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL