server:
  port: 18888

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  config: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: oracle

